cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
)

cc_binary(
    name = "helloworld.js",
    srcs = ["hello-world.cc"],
    features = ["toolchain_include_directories"],
    # copts = [
    #     "-isystem",
    #     "external/emscripten_toolchain/system/include/libcxx",
    #     "-isystem",
    #     "external/emscripten_toolchain/system/include/libc",
    # ],
)
